import { useState } from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler,
} from 'chart.js';
import type { DashboardData } from './types';
import { Header } from './components/Header';
import { TabBar } from './components/TabBar';
import { TeamView } from './components/TeamView';
import { DetailView } from './components/DetailView';
import { FullTable } from './components/FullTable';
import { ConfigView } from './components/ConfigView';

ChartJS.register(
  CategoryScale, LinearScale, BarElement, PointElement, LineElement,
  Title, Tooltip, Legend, Filler,
);

interface AppProps {
  data: DashboardData;
}

export default function App({ data }: AppProps) {
  const [activeTab, setActiveTab] = useState('team');

  return (
    <>
      <Header
        title={data.title}
        subtitle={data.subtitle}
        generated={data.generated}
        isCurrentQuarter={data.isCurrentQuarter}
      />
      <div className="container">
        <TabBar activeTab={activeTab} onTabChange={setActiveTab} />
        {activeTab === 'team' && (
          <TeamView
            quarters={data.quarters}
            currentQuarterIndex={data.currentQuarterIndex}
            isCurrentQuarter={data.isCurrentQuarter}
            hasScoring={data.hasScoring}
            hasJira={data.hasJira}
          />
        )}
        {activeTab === 'overview' && (
          <DetailView
            quarters={data.quarters}
            names={data.names}
            colors={data.colors}
            currentQuarterIndex={data.currentQuarterIndex}
            isCurrentQuarter={data.isCurrentQuarter}
            hasScoring={data.hasScoring}
            hasJira={data.hasJira}
          />
        )}
        {activeTab === 'table' && (
          <FullTable
            tableRows={data.tableRows}
            quarterLabels={data.quarterLabels}
            hasScoring={data.hasScoring}
            hasJira={data.hasJira}
          />
        )}
        {activeTab === 'config' && (
          <ConfigView
            config={data.config}
            hasScoring={data.hasScoring}
          />
        )}
      </div>
      <div className="footer">Generated by teamdash &middot; {data.generated}</div>
    </>
  );
}
